name: Build with DevkitPro

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [devkitarm, devkitppc]   # devkitARM = GBA/NDS, devkitPPC = Wii/GameCube
    container:
      image: devkitpro/${{ matrix.target }}:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build project
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=${DEVKITPRO}/devkitARM
          export DEVKITPPC=${DEVKITPRO}/devkitPPC
          ls # debug
          chmod +x build.sh
          ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
              build/*.elf
              build/*.bin
